"""20230515_12_11

Revision ID: 1126d8e011bb
Revises: 131dd4038563
Create Date: 2023-05-15 12:11:58.037018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1126d8e011bb'
down_revision = '131dd4038563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_employee', sa.Column('is_active_employee', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_employee', 'is_active_employee')
    # ### end Alembic commands ###
