"""20230511_1444

Revision ID: 131dd4038563
Revises: 693389a5aa5f
Create Date: 2023-05-11 14:44:06.018242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131dd4038563'
down_revision = '693389a5aa5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_employee', sa.Column('area', sa.String(length=10), nullable=True))
    op.add_column('tbl_employee', sa.Column('process', sa.String(length=10), nullable=True))
    op.add_column('tbl_employee', sa.Column('Type_Relationship', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_employee', 'Type_Relationship')
    op.drop_column('tbl_employee', 'process')
    op.drop_column('tbl_employee', 'area')
    # ### end Alembic commands ###
