"""Firts Migration 20230505_1459

Revision ID: 693389a5aa5f
Revises: 
Create Date: 2023-05-05 15:02:18.124099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693389a5aa5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_employee',
    sa.Column('ccn_employee', sa.Integer(), nullable=False),
    sa.Column('number_id_employee', sa.BigInteger(), nullable=False),
    sa.Column('full_name_employee', sa.String(length=200), nullable=False),
    sa.Column('ccn_role', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('informed_consent_law_1581', sa.String(length=10), nullable=False),
    sa.Column('employee_password', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('ccn_employee')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_employee')
    # ### end Alembic commands ###
