"""20230606_1335

Revision ID: f70613a29f91
Revises: 1126d8e011bb
Create Date: 2023-06-06 13:35:26.134646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f70613a29f91'
down_revision = '1126d8e011bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_employee', sa.Column('area', sa.String(length=10), nullable=True))
    op.add_column('tbl_employee', sa.Column('process', sa.String(length=10), nullable=True))
    op.add_column('tbl_employee', sa.Column('Type_Relationship', sa.String(length=10), nullable=True))
    op.add_column('tbl_employee', sa.Column('is_active_employee', sa.Boolean(), nullable=True))
    op.alter_column('tbl_employee', 'ccn_role',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('tbl_employee', 'role',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_employee', 'role',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('tbl_employee', 'ccn_role',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_column('tbl_employee', 'is_active_employee')
    op.drop_column('tbl_employee', 'Type_Relationship')
    op.drop_column('tbl_employee', 'process')
    op.drop_column('tbl_employee', 'area')
    # ### end Alembic commands ###
